### ISSUE TITLE
Update padlock icon in CC form to use icon font code

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#2458]
The padlock icon that is displayed in the credit card form when on ssl should be updated to use an action font icon instead of the glyph code. Something like this:

``` css
#edd_secure_site_wrapper span.padlock:before {
font-family: 'Genericons';
content: '\f470';
}
```

The glyph code appears to be breaking in Chrome on Windows, at least for some users.

https://easydigitaldownloads.com/support/topic/ssl-padlock-icon-in-chrome/page/2/#post-277398
