### ISSUE TITLE
Vertical Align .edd_repetable_row td

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/Easy-Digital-Downloads#2991]
```css
.edd_repeatable_row td {
vertical-align: middle;
}
```

Makes quite a nice difference.
