### ISSUE TITLE
Checkout error messages

### ISSUE THREAD

**Issue by shazahm1** [easydigitaldownloads/Easy-Digital-Downloads#345]
This might be by design, but, currently the error messages in the checkout process can be easily missed by the user because they are not really called out visually. Here's the CSS I used to call them out to the user. If you agree, maybe it can be added to EDD.

``` css
/*
 * Checkout Error Messages
 */
.edd_errors {
    -webkit-border-radius: 1px;
    -moz-border-radius: 1px;
    border-radius: 1px;
    border: 1px solid #BBB;
    margin: 20px 0;
    background: #FDE9EA;
    color: #A14A40;
    border-color: #FDCED0;
}
.edd_error {
    border: 1px solid #fff;
    padding:10px;
}
p.edd_error {
    margin: 0 !important; /* important added to keep theme from adding the margin */
}
```
