### ISSUE TITLE
Improve CSS shorthand consistency in templates/edd.css

### ISSUE THREAD

**Issue by christ0ph3r** [easydigitaldownloads/Easy-Digital-Downloads#3792]
I was checking out templates/edd.css and noticed a couple margin properties aren't using shorthand methods while most of them are. I found 3 that weren't. I am unsure if this matters though since they are minified into their shorthand values. It can improve consistency/readability though for the non minified file.   #edd_checkout_form_wrap fieldset and #edd_checkout_form_wrap legend are 2 examples that could be optimzied. I also noticed they use the same margin values and are both located in the checkout fields section so they could potentially be combined.

Currently :
```css
#edd_checkout_form_wrap legend {
    margin: 0 0 21px 0;
}
#edd_checkout_form_wrap fieldset {
    margin: 0 0 21px 0;
}
```

Could be:
```css
#edd_checkout_form_wrap legend, #edd_checkout_form_wrap fieldset {
    margin: 0 0 21px;
}
```

Update:  After further research I think I may of mispoke.  Shorthand is using just one property which is the case here.  What I meant to say is that property can have less values.  So instead of 4 values it could have 3 in this case.
