### ISSUE TITLE
Adding display:none to price options breaks add to cart jQuery

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4653]
Alright, this is one of the stranger bugs I've seen.

Let's say you have a download product with 5 price options, like this:
![screen shot 2016-06-02 at 7 45 37 pm](https://cloud.githubusercontent.com/assets/1034109/15765454/a235cd86-28fa-11e6-9277-8e62d551f829.png)

Now, for one reason or another, you decide that you want to hide the last two price options using CSS:
```css
.edd_price_options ul li:nth-child(4), .edd_price_options ul li:nth-child(5), .edd_price_options ul li:nth-child(6) {
	display: none;
}
```
This results in the price options rendering like this:
![screen shot 2016-06-02 at 7 46 50 pm](https://cloud.githubusercontent.com/assets/1034109/15765472/c4da8bba-28fa-11e6-9975-e714931baf71.png)

So far so good.

Now a customer comes along and selects `Price Three` and clicks add to cart. The cart widget and checkout now show that you have actually added `Price One` to the cart:

![screen shot 2016-06-02 at 7 48 03 pm](https://cloud.githubusercontent.com/assets/1034109/15765487/f0c76ebe-28fa-11e6-97b9-b2c209229f0e.png)

It does not matter which price option is selected, the first price option will _always_ be added to the cart so long as the CSS above is on the site.

Now, if that CSS is changed to this, it works fine:
```css
.edd_price_options ul li:nth-child(4), .edd_price_options ul li:nth-child(5), .edd_price_options ul li:nth-child(6) {
	height: 0;
	width: 0;
	overflow: hidden;
}
```
This CSS also works:
```css
.edd_price_options ul li:nth-child(4), .edd_price_options ul li:nth-child(5), .edd_price_options ul li:nth-child(6) {
	visibility: hidden;
}
```

The JS that handles the add to cart process is in `edd-ajax.js`. Here's the relevant section:
```js
if( variable_price == 'yes' ) {

	if ( form.find('.edd_price_option_' + download).is('input:hidden') ) {
		item_price_ids[0] = $('.edd_price_option_' + download, form).val();
		if ( form.find('.edd-submit').data('price') && form.find('.edd-submit').data('price') > 0 ) {
			free_items = false;
		}
	} else {
		if( ! form.find('.edd_price_option_' + download + ':checked', form).length ) {
			 // hide the spinner
			$this.removeAttr( 'data-edd-loading' );
			alert( edd_scripts.select_option );
			return;
		}

		form.find('.edd_price_option_' + download + ':checked', form).each(function( index ) {
			item_price_ids[ index ] = $(this).val();

			// If we're still only at free items, check if this one is free also
			if ( true === free_items ) {
				var item_price = $(this).data('price');
				if ( item_price && item_price > 0 ) {
					// We now have a paid item, we can't use add_to_cart
					free_items = false;
				}
			}

		});
	}

}
```

It appears that the `display:none` is effecting jQuery's ability to return proper results with `.find()`, but I have no idea why.
