### ISSUE TITLE
Make Chosen.js matches wordpress style

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/easy-digital-downloads#5388]
EDD and other plugins uses this js resources (built-in edd core)

I know this is a really low priority but with a few lines of code we can made this matches same style like wordpress inputs

```css
.chosen-container .chosen-single,
.chosen-container .chosen-drop {
    border: 1px solid #ddd;
    -webkit-box-shadow: inset 0 1px 2px rgba(0,0,0,.07);
    box-shadow: inset 0 1px 2px rgba(0,0,0,.07);
    background: #fff;
    border-radius: 0;
}

.chosen-container .chosen-single {
    padding: 3px 5px;
}

.chosen-container .chosen-drop {
    border-top: none;
}

.chosen-container-active.chosen-with-drop .chosen-single {
    background: #fff;
}

.chosen-container .chosen-results li.highlighted {
    background: #0073aa;
}
```
