### ISSUE TITLE
3.0 - Update Date Range Styles to Match Core

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#8065]
### Explain your enhancement (please be detailed)

Update input date range styles to match WordPress 5.2+ styles.

### Justification or use case

Current CSS styles cause the inputs to look broken:

<img width="210" alt="Screen Shot 2020-07-22 at 12 13 36 PM" src="https://user-images.githubusercontent.com/491124/88200928-d1d48700-cc14-11ea-8d43-7b72455f7c2a.png">

**Comment by spencerfinnell** [comment]
I believe the following will allow styles to apply correct to all versions:

``` css
.edd-from-to-wrapper input:focus {
	z-index: 2;
	position: relative;
}

.edd-from-to-wrapper input[name="start"],
.edd-from-to-wrapper input[name="start-date"],
.edd-from-to-wrapper input[name="filter_from"] {
	border-top-right-radius: 0;
	border-bottom-right-radius: 0;
}

.edd-from-to-wrapper input[name="end"],
.edd-from-to-wrapper input[name="end-date"],
.edd-from-to-wrapper input[name="filter_to"] {
	margin-left: -1px;
	border-top-left-radius: 0;
	border-bottom-left-radius: 0;
}
```

<img width="207" alt="Screen Shot 2020-07-22 at 12 15 44 PM" src="https://user-images.githubusercontent.com/491124/88201273-40b1e000-cc15-11ea-82ae-387e4b5927e3.png">
<img width="209" alt="Screen Shot 2020-07-22 at 12 16 30 PM" src="https://user-images.githubusercontent.com/491124/88201275-414a7680-cc15-11ea-8f80-0d969e4c1a98.png">
